
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otp
  template:
    metadata:
      labels:
        app: otp
    spec:
      containers:
      - name: otp
        image: otp-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: OTP_TTL
          valueFrom:
            configMapKeyRef:
              name: otp-config
              key: ttl